apiVersion: v1
data:
  crpd-custom-config.tmpl: ""
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: jcnr
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-12-27T09:47:46Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: jcnr-custom-config
  namespace: jcnr
  uid: 0e9220bc-96a9-481a-a85f-d6a0429aab4f
