apiVersion: v1
count: 38870
eventTime: null
firstTimestamp: "2023-12-27T09:48:02Z"
involvedObject:
  apiVersion: v1
  kind: Pod
  name: syslog-ng-k4hcw
  namespace: jcnr
  resourceVersion: "1245"
  uid: 9f969483-ed77-4f2c-b880-9c8e0da7cdf7
kind: Event
lastTimestamp: "2024-01-30T10:08:04Z"
message: 'Nameserver limits were exceeded, some nameservers have been omitted, the
  applied nameserver line is: 10.84.5.101 172.21.200.60 66.129.233.81'
metadata:
  creationTimestamp: "2023-12-27T09:48:02Z"
  name: syslog-ng-k4hcw.17a4a7471dd8af0b
  namespace: jcnr
  uid: 8d25af4d-49a9-4892-bb23-9aa9d60eddd3
reason: DNSConfigForming
reportingComponent: kubelet
reportingInstance: sharmag-k8s-master-pnad30.englab.juniper.net
source:
  component: kubelet
  host: sharmag-k8s-master-pnad30.englab.juniper.net
type: Warning
