apiVersion: v1
count: 39283
eventTime: null
firstTimestamp: "2023-12-27T09:47:48Z"
involvedObject:
  apiVersion: v1
  kind: Pod
  name: kube-crpd-worker-sts-2
  namespace: jcnr
  resourceVersion: "1317"
  uid: f8fe369d-92b5-4823-9f14-4fd3057931d8
kind: Event
lastTimestamp: "2024-01-30T16:33:04Z"
message: 'Nameserver limits were exceeded, some nameservers have been omitted, the
  applied nameserver line is: 10.84.5.101 172.21.200.60 66.129.233.81'
metadata:
  creationTimestamp: "2023-12-27T09:47:48Z"
  name: kube-crpd-worker-sts-2.17a4a743bafea299
  namespace: jcnr
  uid: fb90158a-9523-4620-a4f2-d968798a38da
reason: DNSConfigForming
reportingComponent: kubelet
reportingInstance: sharmag-k8s-master-pnad30.englab.juniper.net
source:
  component: kubelet
  host: sharmag-k8s-master-pnad30.englab.juniper.net
type: Warning
