apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2023-12-27T09:47:47Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    k8s-app: kube-crpd-worker
  name: conf-kube-crpd-worker-sts-0
  namespace: jcnr
  uid: 261631fc-dc39-4449-98a7-7d606265d8a5
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  storageClassName: jcnrstorage
  volumeMode: Filesystem
  volumeName: jcnr-pv-volume-2
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 256Mi
  phase: Bound
