addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints:
- addresses:
  - 10.244.35.139
  conditions:
    ready: true
    serving: true
    terminating: false
  nodeName: sharmag-k8s-dpdk-kubelet1-pnad30.englab.juniper.net
  targetRef:
    kind: Pod
    name: coredns-756994469c-pxnkd
    namespace: kube-system
    uid: a5fa52ee-7a54-432c-9a48-cc69eda3eee5
- addresses:
  - 10.244.100.204
  conditions:
    ready: true
    serving: true
    terminating: false
  nodeName: sharmag-k8s-master-pnad30.englab.juniper.net
  targetRef:
    kind: Pod
    name: coredns-756994469c-d5xlj
    namespace: kube-system
    uid: 01eaa7b9-9806-4321-8173-3cd80a4e1f5c
kind: EndpointSlice
metadata:
  creationTimestamp: "2023-12-27T09:43:05Z"
  generateName: kube-dns-
  labels:
    endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: CoreDNS
    kubernetes.io/service-name: kube-dns
  name: kube-dns-z98s5
  namespace: kube-system
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Service
    name: kube-dns
    uid: 66e74669-d4b3-412d-a768-b712390992fc
  uid: 5d96b002-38b3-45cc-882f-aca577b31f2e
ports:
- name: metrics
  port: 9153
  protocol: TCP
- name: dns
  port: 53
  protocol: UDP
- name: dns-tcp
  port: 53
  protocol: TCP
