apiVersion: events.k8s.io/v1
deprecatedCount: 39209
deprecatedFirstTimestamp: "2023-12-27T09:47:05Z"
deprecatedLastTimestamp: "2024-01-30T16:33:13Z"
deprecatedSource:
  component: kubelet
  host: sharmag-k8s-dpdk-kubelet1-pnad30.englab.juniper.net
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2023-12-27T09:47:05Z"
  name: kube-multus-ds-kvhj4.17a4a739be965577
  namespace: kube-system
  uid: a3fa6032-7bf4-4a1a-a186-a96fef748aae
note: 'Nameserver limits were exceeded, some nameservers have been omitted, the applied
  nameserver line is: 10.84.5.101 172.21.200.60 66.129.233.81'
reason: DNSConfigForming
regarding:
  apiVersion: v1
  kind: Pod
  name: kube-multus-ds-kvhj4
  namespace: kube-system
  resourceVersion: "1078"
  uid: 106cfd03-50ca-4e15-978f-86797c14d6eb
reportingController: kubelet
reportingInstance: sharmag-k8s-dpdk-kubelet1-pnad30.englab.juniper.net
type: Warning
