apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2023-12-27T09:42:47Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:token-cleaner
  namespace: kube-system
  uid: 4e93b8f9-53e7-4311-b046-7de8c0acde04
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: system:controller:token-cleaner
subjects:
- kind: ServiceAccount
  name: token-cleaner
  namespace: kube-system
