apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: "2023-12-27T09:42:49Z"
  name: kube-proxy
  namespace: kube-system
  uid: a2403c28-fba7-49e3-9afb-429cba06b48c
rules:
- apiGroups:
  - ""
  resourceNames:
  - kube-proxy
  resources:
  - configmaps
  verbs:
  - get
