apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: "2023-12-27T09:42:47Z"
  name: kubeadm:nodes-kubeadm-config
  namespace: kube-system
  uid: ceaaf043-3c2d-4206-9a11-b72cca0fb635
rules:
- apiGroups:
  - ""
  resourceNames:
  - kubeadm-config
  resources:
  - configmaps
  verbs:
  - get
