apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2023-12-27T09:43:01Z"
  name: clusterrole-aggregation-controller
  namespace: kube-system
  uid: c75b55ec-e15b-40b2-8f3a-356ffd9c3bfd
