apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  creationTimestamp: "2023-12-27T09:42:46Z"
  labels:
    kube-aggregator.kubernetes.io/automanaged: onstart
  name: v1.apps
  uid: e7d4766b-6e2a-4dbb-9644-99eb85aa884e
spec:
  group: apps
  groupPriorityMinimum: 17800
  version: v1
  versionPriority: 15
status:
  conditions:
  - lastTransitionTime: "2023-12-27T09:42:46Z"
    message: Local APIServices are always available
    reason: Local
    status: "True"
    type: Available
