apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  creationTimestamp: "2023-12-27T09:42:46Z"
  labels:
    kube-aggregator.kubernetes.io/automanaged: onstart
  name: v1.rbac.authorization.k8s.io
  uid: da35d692-ad19-40ea-a509-cfc481de8061
spec:
  group: rbac.authorization.k8s.io
  groupPriorityMinimum: 17000
  version: v1
  versionPriority: 15
status:
  conditions:
  - lastTransitionTime: "2023-12-27T09:42:46Z"
    message: Local APIServices are always available
    reason: Local
    status: "True"
    type: Available
