apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2023-12-27T09:42:47Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:service-controller
  uid: 4190dce3-e487-4233-9cd3-16720a0f4add
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:controller:service-controller
subjects:
- kind: ServiceAccount
  name: service-controller
  namespace: kube-system
