apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2023-12-27T09:42:48Z"
  name: kubeadm:get-nodes
  uid: e5c07566-4870-497f-96b3-a3e1af8e0e0f
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
