apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2023-12-27T09:42:47Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:resourcequota-controller
  uid: 3bffc683-496c-4ac8-bad3-018ca716c42e
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:controller:resourcequota-controller
subjects:
- kind: ServiceAccount
  name: resourcequota-controller
  namespace: kube-system
