apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: jcnr
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-12-27T09:47:46Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: contrail-role
  uid: 36519a6a-ae70-4548-87b3-275f30d20659
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
