apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRoleBinding","metadata":{"annotations":{},"labels":{"app":"katafygio","chart":"katafygio-0.5.1","heritage":"Helm","release":"katafygio"},"name":"katafygio"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"katafygio"},"subjects":[{"kind":"ServiceAccount","name":"katafygio","namespace":"default"}]}
  creationTimestamp: "2024-01-16T06:58:52Z"
  labels:
    app: katafygio
    chart: katafygio-0.5.1
    heritage: Helm
    release: katafygio
  name: katafygio
  uid: 74466ed9-25a5-4af3-81a2-d47e6547186c
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: katafygio
subjects:
- kind: ServiceAccount
  name: katafygio
  namespace: default
