apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "10"
  creationTimestamp: "2023-12-27T09:47:46Z"
  labels:
    jcnr: "true"
  name: ops-rolebinding
  uid: f8d81952-7b8f-4541-860d-57ea3d3a97fd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ops-role
subjects:
- kind: ServiceAccount
  name: ops-serviceaccount
  namespace: jcnr
