apiVersion: crd.projectcalico.org/v1
kind: IPAMBlock
metadata:
  annotations:
    projectcalico.org/metadata: '{"creationTimestamp":null}'
  creationTimestamp: "2023-12-27T09:46:30Z"
  name: 10-244-35-128-26
  uid: dbe8a720-d274-4586-a2ac-4cdb9b856ac3
spec:
  affinity: host:sharmag-k8s-dpdk-kubelet1-pnad30.englab.juniper.net
  allocations:
  - 0
  - 1
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - 2
  - null
  - 3
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  attributes:
  - handle_id: ipip-tunnel-addr-sharmag-k8s-dpdk-kubelet1-pnad30.englab.juniper.net
    secondary:
      node: sharmag-k8s-dpdk-kubelet1-pnad30.englab.juniper.net
      type: ipipTunnelAddress
  - handle_id: k8s-pod-network.9cc9e4d3c9bf0275d64656a22532559737013c41dc38e39145dbf3ad1d69952d
    secondary:
      namespace: kube-system
      node: sharmag-k8s-dpdk-kubelet1-pnad30.englab.juniper.net
      pod: calico-kube-controllers-86f8947565-db7lp
      timestamp: 2023-12-27 09:46:41.455762656 +0000 UTC
  - handle_id: k8s-pod-network.9d898d65e8fd325b91de92d7095ffb2f5177dcb367431d648222b37da89cca92
    secondary:
      namespace: default
      node: sharmag-k8s-dpdk-kubelet1-pnad30.englab.juniper.net
      pod: example-webhook-66f6b79986-kz685
      timestamp: 2024-01-15 12:15:53.670018212 +0000 UTC
  - handle_id: k8s-pod-network.fa5fd50518186c335be52bf1b9e74e2ea3b5d31b3839d8dd67f04e9a242fcfae
    secondary:
      namespace: kube-system
      node: sharmag-k8s-dpdk-kubelet1-pnad30.englab.juniper.net
      pod: coredns-756994469c-pxnkd
      timestamp: 2024-01-15 18:12:06.570463574 +0000 UTC
  cidr: 10.244.35.128/26
  deleted: false
  sequenceNumber: 1703670390757791005
  sequenceNumberForAllocation:
    "0": 1703670390757790985
    "1": 1703670390757790986
    "2": 1703670390757790987
    "3": 1703670390757790989
    "4": 1703670390757790991
    "5": 1703670390757790993
    "6": 1703670390757790995
    "7": 1703670390757790997
    "8": 1703670390757790999
    "9": 1703670390757791001
    "10": 1703670390757791002
    "11": 1703670390757791003
  strictAffinity: false
  unallocated:
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20
  - 21
  - 22
  - 23
  - 24
  - 25
  - 26
  - 27
  - 28
  - 29
  - 30
  - 31
  - 32
  - 33
  - 34
  - 35
  - 36
  - 37
  - 38
  - 39
  - 40
  - 41
  - 42
  - 43
  - 44
  - 45
  - 46
  - 47
  - 48
  - 49
  - 50
  - 51
  - 52
  - 53
  - 54
  - 55
  - 56
  - 57
  - 58
  - 59
  - 60
  - 61
  - 62
  - 63
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 10
