apiVersion: v1
kind: Namespace
metadata:
  annotations:
    meta.helm.sh/release-name: jcnr
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-12-27T09:47:46Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    kubernetes.io/metadata.name: contrail-system
  name: contrail-system
  uid: c96c5dd4-0772-4225-9019-fab92ada042f
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
