apiVersion: v1
kind: Namespace
metadata:
  annotations:
    meta.helm.sh/release-name: jcnr
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-12-27T09:47:46Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    kubernetes.io/metadata.name: contrail-deploy
  name: contrail-deploy
  uid: 723842e9-315f-4c62-ac31-392a588fa0b3
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
