apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{},"name":"git-pv"},"spec":{"accessModes":["ReadWriteOnce"],"capacity":{"storage":"5Gi"},"hostPath":{"path":"/tmp"},"persistentVolumeReclaimPolicy":"Retain","storageClassName":"jcnrstorage","volumeMode":"Filesystem"}}
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2024-01-30T10:20:03Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: git-pv
  uid: 380eb29d-2137-429d-82b0-5daa2f37f348
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: git-volume
    namespace: default
    resourceVersion: "4323595"
    uid: 55c911da-357e-41b0-b85f-50642f2baa18
  hostPath:
    path: /tmp
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jcnrstorage
  volumeMode: Filesystem
status:
  phase: Bound
