apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    meta.helm.sh/release-name: jcnr
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-12-27T09:47:46Z"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    app.kubernetes.io/managed-by: Helm
  name: jcnr-pv-volume-1
  uid: b8580a6f-49a4-4b4c-b1dc-8a0c65f353d4
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 256Mi
  hostPath:
    path: /etc/crpd
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jcnrstorage
  volumeMode: Filesystem
status:
  phase: Available
