apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{},"name":"git-pv"},"spec":{"accessModes":["ReadWriteOnce"],"capacity":{"storage":"5Gi"},"hostPath":{"path":"/tmp"},"persistentVolumeReclaimPolicy":"Retain","storageClassName":"jcnrstorage","volumeMode":"Filesystem"}}
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2024-01-25T05:51:55Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: git-pv
  uid: 14a1f0f6-5bd2-4373-8fd1-29e253d32652
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: git-volume
    namespace: default
    resourceVersion: "3669297"
    uid: f92d1d85-7618-4a36-9ebc-8b4bf53d036f
  hostPath:
    path: /tmp
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jcnrstorage
  volumeMode: Filesystem
status:
  phase: Bound
