apiVersion: flowcontrol.apiserver.k8s.io/v1beta2
kind: PriorityLevelConfiguration
metadata:
  annotations:
    apf.kubernetes.io/autoupdate-spec: "true"
  creationTimestamp: "2023-12-27T09:42:46Z"
  name: node-high
  uid: ee0e2697-39c7-4705-88ed-e74e95b02f26
spec:
  limited:
    assuredConcurrencyShares: 40
    lendablePercent: 25
    limitResponse:
      queuing:
        handSize: 6
        queueLengthLimit: 50
        queues: 64
      type: Queue
  type: Limited
status: {}
