apiVersion: flowcontrol.apiserver.k8s.io/v1beta2
kind: PriorityLevelConfiguration
metadata:
  annotations:
    apf.kubernetes.io/autoupdate-spec: "true"
  creationTimestamp: "2023-12-27T09:42:46Z"
  name: global-default
  uid: 60b9b0bf-fc9b-4fa9-b6a5-76c7825c865a
spec:
  limited:
    assuredConcurrencyShares: 20
    lendablePercent: 50
    limitResponse:
      queuing:
        handSize: 6
        queueLengthLimit: 50
        queues: 128
      type: Queue
  type: Limited
status: {}
