apiVersion: flowcontrol.apiserver.k8s.io/v1beta2
kind: PriorityLevelConfiguration
metadata:
  annotations:
    apf.kubernetes.io/autoupdate-spec: "true"
  creationTimestamp: "2023-12-27T09:42:46Z"
  name: workload-high
  uid: 1cb0f86b-42f1-469f-b002-3a300985d636
spec:
  limited:
    assuredConcurrencyShares: 40
    lendablePercent: 50
    limitResponse:
      queuing:
        handSize: 6
        queueLengthLimit: 50
        queues: 128
      type: Queue
  type: Limited
status: {}
