apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2024-01-30T10:20:44Z"
  creationTimestamp: "2024-01-30T10:20:44Z"
  name: gitea-service
  namespace: default
  uid: 7a8d5538-bb44-4693-ac3e-94280811e193
subsets:
- addresses:
  - ip: 10.244.35.154
    nodeName: sharmag-k8s-dpdk-kubelet1-pnad30.englab.juniper.net
    targetRef:
      kind: Pod
      name: gitea-7c6954fdcd-6lj4s
      namespace: default
      uid: 5e95cecf-27fa-42bf-8d66-aa1e10c89b76
  ports:
  - port: 3000
    protocol: TCP
