apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2024-01-15T12:15:59Z"
  creationTimestamp: "2024-01-15T12:15:53Z"
  name: example-webhook
  namespace: default
  uid: b25660e3-80fe-4ce5-93d9-496f28a94959
subsets:
- addresses:
  - ip: 10.244.35.137
    nodeName: sharmag-k8s-dpdk-kubelet1-pnad30.englab.juniper.net
    targetRef:
      kind: Pod
      name: example-webhook-66f6b79986-kz685
      namespace: default
      uid: d83cbb0c-6d4b-48d7-b496-99f4d83e568c
  ports:
  - name: application
    port: 8443
    protocol: TCP
  - name: metrics
    port: 80
    protocol: TCP
