apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: "2023-12-27T09:42:47Z"
  labels:
    endpointslice.kubernetes.io/skip-mirror: "true"
  name: kubernetes
  namespace: default
  uid: 0a88dded-035d-4b62-824f-82dd313ab2c1
subsets:
- addresses:
  - ip: 192.168.1.2
  ports:
  - name: https
    port: 6443
    protocol: TCP
