apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2024-01-30T06:00:55Z"
  creationTimestamp: "2024-01-30T06:00:55Z"
  name: gitea-service
  namespace: default
  uid: 83c13af0-e9d1-4748-b272-4e770294d6b8
subsets:
- addresses:
  - ip: 10.244.35.153
    nodeName: sharmag-k8s-dpdk-kubelet1-pnad30.englab.juniper.net
    targetRef:
      kind: Pod
      name: gitea-7c6954fdcd-ftscd
      namespace: default
      uid: bf6594de-c40b-4d72-b1f5-d48af978681f
  ports:
  - port: 3000
    protocol: TCP
