apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2024-01-19T18:50:16Z"
  creationTimestamp: "2024-01-19T18:50:14Z"
  name: example-webhook
  namespace: default
  uid: a425dbfb-d81c-4fc4-b7ee-ea071fa7d666
subsets:
- addresses:
  - ip: 10.244.35.152
    nodeName: sharmag-k8s-dpdk-kubelet1-pnad30.englab.juniper.net
    targetRef:
      kind: Pod
      name: example-webhook-759d9786bf-824tf
      namespace: default
      uid: 7c55a636-9bd9-4652-9af8-65dcc95dbb5a
  ports:
  - name: application
    port: 8443
    protocol: TCP
  - name: metrics
    port: 80
    protocol: TCP
