apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"git-volume","namespace":"default"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"5Gi"}},"storageClassName":"jcnrstorage","volumeName":"git-pv"}}
    pv.kubernetes.io/bind-completed: "yes"
  creationTimestamp: "2024-01-30T10:20:09Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: git-volume
  namespace: default
  uid: 55c911da-357e-41b0-b85f-50642f2baa18
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: jcnrstorage
  volumeMode: Filesystem
  volumeName: git-pv
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  phase: Bound
