apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 529276902baaec7baf52fa6782a71573d401ce88052dce11cde35e59ab12406c
    cni.projectcalico.org/podIP: 10.244.35.154/32
    cni.projectcalico.org/podIPs: 10.244.35.154/32
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "10.244.35.154"
          ],
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "10.244.35.154"
          ],
          "default": true,
          "dns": {}
      }]
  creationTimestamp: "2024-01-30T10:20:09Z"
  generateName: gitea-7c6954fdcd-
  labels:
    app: gitea
    pod-template-hash: 7c6954fdcd
  name: gitea-7c6954fdcd-6lj4s
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: gitea-7c6954fdcd
    uid: 4116c098-a389-40cf-bdc6-3d0c12d83984
  uid: 5e95cecf-27fa-42bf-8d66-aa1e10c89b76
spec:
  containers:
  - image: svl-artifactory.juniper.net/atom-docker/cn2/trohit7/gitea/gitea:1.21.4-rootless
    imagePullPolicy: IfNotPresent
    name: gitea
    ports:
    - containerPort: 3000
      name: gitea
      protocol: TCP
    - containerPort: 22
      name: git-ssh
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /data
      name: git-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-rtx8q
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: sharmag-k8s-dpdk-kubelet1-pnad30.englab.juniper.net
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: git-volume
    persistentVolumeClaim:
      claimName: git-volume
  - name: kube-api-access-rtx8q
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-01-30T10:20:16Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-01-30T10:20:17Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-01-30T10:20:17Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-01-30T10:20:16Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://04541cdb383da20a50165cb8c818872a5e21cf7e53ebd7f9f828bf8b59d23a5d
    image: svl-artifactory.juniper.net/atom-docker/cn2/trohit7/gitea/gitea:1.21.4-rootless
    imageID: b54bb0997f8c4c7a1bfc57640afe1b0c79065097e1e92889babcfaa6c18d6ae6
    lastState: {}
    name: gitea
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-01-30T10:20:17Z"
  hostIP: 192.168.1.3
  phase: Running
  podIP: 10.244.35.154
  podIPs:
  - ip: 10.244.35.154
  qosClass: BestEffort
  startTime: "2024-01-30T10:20:16Z"
