apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"example-webhook","namespace":"default"}}
  creationTimestamp: "2024-01-19T18:44:35Z"
  name: example-webhook
  namespace: default
  uid: 2e257a8a-2b9c-4223-a9c5-5ebcd89dfeeb
