apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"example-webhook","namespace":"default"},"spec":{"ports":[{"name":"application","port":443,"targetPort":8443},{"name":"metrics","port":80,"targetPort":"metrics"}],"selector":{"app":"example-webhook"}}}
  creationTimestamp: "2024-01-15T12:15:53Z"
  name: example-webhook
  namespace: default
  uid: 96a0567a-0110-4a86-b1ce-7ee34e439b66
spec:
  clusterIP: 10.10.10.150
  clusterIPs:
  - 10.10.10.150
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: application
    port: 443
    protocol: TCP
    targetPort: 8443
  - name: metrics
    port: 80
    protocol: TCP
    targetPort: metrics
  selector:
    app: example-webhook
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
