apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app":"katafygio","chart":"katafygio-0.5.1","heritage":"Helm","release":"katafygio"},"name":"katafygio","namespace":"default"}}
  creationTimestamp: "2024-01-16T06:58:52Z"
  labels:
    app: katafygio
    chart: katafygio-0.5.1
    heritage: Helm
    release: katafygio
  name: katafygio
  namespace: default
  uid: d8a71cd4-5974-4678-9a50-dd088a3d38fa
