apiVersion: v1
data:
  127.0.0.1: "5269"
kind: ConfigMap
metadata:
  creationTimestamp: "2023-12-27T09:47:54Z"
  name: dynamic-config-configmap
  namespace: contrail
  uid: b4124d4a-9324-4445-93f4-99fe93b820cf
