apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: jcnr
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-12-27T09:47:46Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: contrail-serviceaccount
  namespace: contrail
  uid: 2aac71f2-4891-453a-a8ab-c349f2bc5526
